name: socket-server ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      #- name: Docker Login
      #  uses: docker/login-action@v1.8.0
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      #- name: Build and push
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: packages/socket-server
      #    push: true
      #    tags: mtnptrsn/orient-socket-server:latest
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            touch github-actions-has-been-here.txt
            touch github-actions-has-been-here-as-well.txt
